# Generated by Django 5.1.6 on 2025-03-05 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('eval1_score', models.IntegerField()),
                ('eval2_score', models.IntegerField()),
                ('eval3_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressiveEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('eval1_score', models.IntegerField()),
                ('eval2_score', models.IntegerField()),
                ('eval3_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FineEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('eval1_score', models.IntegerField()),
                ('eval2_score', models.IntegerField()),
                ('eval3_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrossEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('eval1_score', models.IntegerField()),
                ('eval2_score', models.IntegerField()),
                ('eval3_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceptiveEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('eval1_score', models.IntegerField()),
                ('eval2_score', models.IntegerField()),
                ('eval3_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelfHelpEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('eval1_score', models.IntegerField()),
                ('eval2_score', models.IntegerField()),
                ('eval3_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('eval1_score', models.IntegerField()),
                ('eval2_score', models.IntegerField()),
                ('eval3_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('handedness', models.CharField(max_length=50)),
                ('studying', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=255)),
                ('father_password', models.CharField(default='123', max_length=128)),
                ('father_age', models.IntegerField()),
                ('father_occupation', models.CharField(max_length=255)),
                ('father_education', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_password', models.CharField(default='123', max_length=128)),
                ('mother_age', models.IntegerField()),
                ('mother_occupation', models.CharField(max_length=255)),
                ('mother_education', models.CharField(max_length=255)),
                ('num_siblings', models.IntegerField()),
                ('birth_order', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_motor', models.FloatField(blank=True, null=True)),
                ('fine_motor', models.FloatField(blank=True, null=True)),
                ('self_help', models.FloatField(blank=True, null=True)),
                ('receptive_language', models.FloatField(blank=True, null=True)),
                ('expressive_language', models.FloatField(blank=True, null=True)),
                ('cognitive', models.FloatField(blank=True, null=True)),
                ('social_emotional', models.FloatField(blank=True, null=True)),
                ('date_assessed', models.DateField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='OBDash.student')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('evaluation_number', models.IntegerField()),
                ('cognitive_score', models.IntegerField()),
                ('fine_motor_score', models.IntegerField()),
                ('gross_motor_score', models.IntegerField()),
                ('self_help_score', models.IntegerField()),
                ('social_emotional_score', models.IntegerField()),
                ('expressive_language_score', models.IntegerField()),
                ('receptive_language_score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBDash.student')),
            ],
            options={
                'unique_together': {('student', 'evaluation_number')},
            },
        ),
    ]
