# Generated by Django 5.1.6 on 2025-03-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBDash', '0002_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfhelpevaluation',
            name='evaluator_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('parent', 'Parent')], default='teacher', max_length=20),
        ),
    ]
