# Generated by Django 5.1.6 on 2025-03-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBDash', '0003_selfhelpevaluation_evaluator_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfhelpevaluation',
            name='evaluator_type',
        ),
    ]
