# Generated by Django 5.1.6 on 2025-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBDash', '0004_remove_selfhelpevaluation_evaluator_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCognitiveEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('eval1_score', models.IntegerField()),
                ('eval2_score', models.IntegerField()),
                ('eval3_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentExpressiveEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('eval1_score', models.IntegerField()),
                ('eval2_score', models.IntegerField()),
                ('eval3_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentGrossEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('eval1_score', models.IntegerField()),
                ('eval2_score', models.IntegerField()),
                ('eval3_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentSelfHelpEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('eval1_score', models.IntegerField()),
                ('eval2_score', models.IntegerField()),
                ('eval3_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentSocialEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('eval1_score', models.IntegerField()),
                ('eval2_score', models.IntegerField()),
                ('eval3_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
