# Generated by Django 5.1.6 on 2025-03-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBDash', '0005_parentcognitiveevaluation_parentexpressiveevaluation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('eval1_total', models.IntegerField()),
                ('eval2_total', models.IntegerField()),
                ('eval3_total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
